/**
 * Lightweight metadata about the question pool.
 * Import this in client components that only need counts
 * to avoid pulling the full ~300KB questions.json into the bundle.
 *
 * AUTO-GENERATED by scripts/generate-questions-meta.mjs — do not edit by hand.
 */
import type { Category, Difficulty } from '@/types/question';

export const QUESTION_COUNT = 217;

export const COUNTS_BY_CATEGORY: Record<Category, number> = {
  'biographical': 67,
  'tone-disconnect': 32,
  'misunderstood-romance': 30,
  'drug-references': 19,
  'historical-political': 27,
  'translation-barriers': 42,
};

export const COUNTS_BY_DIFFICULTY: Record<Difficulty, number> = {
  'medium': 117,
  'easy': 55,
  'hard': 45,
};

const MATRIX: Record<string, number> = {
  'biographical|medium': 38,
  'tone-disconnect|easy': 10,
  'misunderstood-romance|easy': 9,
  'drug-references|medium': 13,
  'historical-political|medium': 17,
  'tone-disconnect|medium': 17,
  'drug-references|hard': 5,
  'biographical|hard': 16,
  'translation-barriers|easy': 18,
  'misunderstood-romance|medium': 16,
  'drug-references|easy': 1,
  'translation-barriers|hard': 8,
  'misunderstood-romance|hard': 5,
  'historical-political|hard': 6,
  'historical-political|easy': 4,
  'translation-barriers|medium': 16,
  'biographical|easy': 13,
  'tone-disconnect|hard': 5,
};

/** Count questions matching optional category and difficulty filters. */
export function countQuestions(
  category: Category | null,
  difficulty: Difficulty | null
): number {
  if (!category && !difficulty) return QUESTION_COUNT;
  if (category && !difficulty) return COUNTS_BY_CATEGORY[category] ?? 0;
  if (!category && difficulty) return COUNTS_BY_DIFFICULTY[difficulty] ?? 0;
  return MATRIX[`${category}|${difficulty}`] ?? 0;
}
