/**
 * Lightweight metadata about the question pool.
 * Import this in client components that only need counts
 * to avoid pulling the full ~300KB questions.json into the bundle.
 *
 * AUTO-GENERATED by scripts/generate-questions-meta.mjs — do not edit by hand.
 */
import type { Category, Difficulty } from '@/types/question';

export const QUESTION_COUNT = 276;

export const COUNTS_BY_CATEGORY: Record<Category, number> = {
  'biographical': 96,
  'tone-disconnect': 40,
  'misunderstood-romance': 35,
  'drug-references': 19,
  'historical-political': 38,
  'translation-barriers': 48,
};

export const COUNTS_BY_DIFFICULTY: Record<Difficulty, number> = {
  'medium': 141,
  'easy': 76,
  'hard': 59,
};

const MATRIX: Record<string, number> = {
  'biographical|medium': 50,
  'tone-disconnect|easy': 12,
  'misunderstood-romance|easy': 11,
  'drug-references|medium': 13,
  'historical-political|medium': 21,
  'tone-disconnect|medium': 23,
  'drug-references|hard': 5,
  'biographical|hard': 25,
  'translation-barriers|easy': 23,
  'misunderstood-romance|medium': 18,
  'drug-references|easy': 1,
  'translation-barriers|hard': 9,
  'misunderstood-romance|hard': 6,
  'historical-political|hard': 9,
  'historical-political|easy': 8,
  'translation-barriers|medium': 16,
  'biographical|easy': 21,
  'tone-disconnect|hard': 5,
};

/** Count questions matching optional category and difficulty filters. */
export function countQuestions(
  category: Category | null,
  difficulty: Difficulty | null
): number {
  if (!category && !difficulty) return QUESTION_COUNT;
  if (category && !difficulty) return COUNTS_BY_CATEGORY[category] ?? 0;
  if (!category && difficulty) return COUNTS_BY_DIFFICULTY[difficulty] ?? 0;
  return MATRIX[`${category}|${difficulty}`] ?? 0;
}
